const randomNumber = Math.floor(Math.random() * 10) + 1;
let remainingAttempts = 3;

const guessField = document.getElementById("guessField");
const guessSubmit = document.getElementById("guessSubmit");
const message = document.getElementById("message");
const imageContainer = document.getElementById("surprise");
const gif = document.getElementById("gif");

// Initially hide the image
imageContainer.style.display = "none";

guessSubmit.addEventListener("click", function () {
  const userGuess = parseInt(guessField.value);

  if (userGuess === randomNumber) {
    message.textContent = "Congratulations! You guessed correctly!";
    guessSubmit.disabled = true;
    // Show the image when the guess is correct
    imageContainer.style.display = "block";
  } else {
    remainingAttempts--;
    if (remainingAttempts === 0) {
      message.textContent = `Sorry, you've used all your attempts. The correct number was ${randomNumber}.`;
      guessSubmit.disabled = true;
    } else {
      const hint = userGuess < randomNumber ? "higher" : "lower";
      message.textContent = `Wrong guess. Try a ${hint} number. Remaining attempts: ${remainingAttempts}`;
    }
  }


}
)


guessSubmit.addEventListener("click", function () {
  const userGuess = parseInt(guessField.value);

if (userGuess === randomNumber) {
  message.textContent = "Surprise!!! Hope you like it!";
  guessSubmit.disabled = true;
  // Show the image when the guess is correct
  imageContainer.style.display = "block";}
}
)








//welcome to the Javascript code for guess my number
//this was all generated by chatGPT 



/*
//the line of code below generates a random number between 1 and 10. 
//you can change 10 to a higher number to make the game harder
const randomNumber = Math.floor(Math.random() * 10) + 1;  
 //you can change the number below to change how many attempts the user gets
let remainingAttempts = 3;  


const guessField = document.getElementById("guessField");
const guessSubmit = document.getElementById("guessSubmit");
const message = document.getElementById("message");



guessSubmit.addEventListener("click", function () {
  const userGuess = parseInt(guessField.value);

  if (userGuess === randomNumber) {
    message.textContent = "Congratulations! You guessed correctly!";
    guessSubmit.disabled = true;
  } else {
    remainingAttempts--;
    if (remainingAttempts === 0) {
      message.textContent = `Sorry, you've used all your attempts. The correct number was ${randomNumber}.`;
      guessSubmit.disabled = true;
    } else {
      const hint = userGuess < randomNumber ? "higher" : "lower";
      message.textContent = `Wrong guess. Try a ${hint} number. Remaining attempts: ${remainingAttempts}`;
    }
  }
});


*/
